apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: arti-test-springboot 
  janus-idp.io/tekton: arti-test-springboot
  backstage.io/kubernetes-id: arti-test-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: arti-test-springboot
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  