apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: arti-test-springboot
  janus-idp.io/tekton: arti-test-springboot
  backstage.io/kubernetes-id: arti-test-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: arti-test-springboot
resources:
- deployment.yaml
- route.yaml
- service.yaml
